# syntax=docker/dockerfile:1

FROM golang:1.25.5-alpine as build

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o scaner cmd/scaner/main.go

FROM alpine

COPY --from=build /app/scaner /app/scaner

CMD ["/app/scaner"]